version: '3.3'

services:

  backend:
    build: ./services/backend
    container_name: fastapi
    ports:
      - "6131:6131"
    volumes:
      - ./services/backend:/app
    command: uvicorn app:app --reload --host 0.0.0.0 --port 6131
    env_file:
      - .env
  frontend:   
   build: ./services/frontend
   container_name: vue
   volumes:
     - ./services/frontend:/app
     - /app/node_modules
   ports:
     - "7001:8080"