version: '3.3'

services:

  backend:
    build: ./services/backend
    container_name: fastapi
    ports:
      - "7001:7001"
    volumes:
      - ./services/backend:/app
    command: uvicorn app:app --reload --host 0.0.0.0 --port 7001
    env_file:
      - .env
    depends_on:
      - db

 # frontend:
 #   build: ./services/frontend
 #   container_name: vue
 #   volumes:
 #     - ./services/frontend:/app
 #     - /app/node_modules
 #   ports:
 #     - "8080:8080"

  db:
    image: postgres:15.1
    container_name: postgres
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${DB_USER-test}
      - POSTGRES_PASSWORD=${DB_PASSWORD-test}
      - POSTGRES_DB=${DB_NAME-test}
    volumes:
      - .postgres_data:/var/lib/postgresql/data/
